version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'braCCe2127'
    ports:
      - "8000:8000"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql